version: 2

checks:
  argument-count:               # Methods or functions defined with a high number of arguments
    config:
      threshold: 10

  # complex-logic:                #  Boolean logic that may be hard to understand
  #   config:
  #     threshold: 4

  file-lines:                   # Excessive lines of code within a single file
    enabled: false
    # config:
      # threshold: 250

  method-complexity:            # Functions or methods that may be hard to understand (Cognitive Complexity)
    config:
      threshold: 50

  # method-count:                 # Classes defined with a high number of functions or methods
  #   config:
  #     threshold: 20

  # method-lines:                 # Excessive lines of code within a single function or method
  #   config:
  #     threshold: 25

  # nested-control-flow:          # Deeply nested control structures like if or case
  #   config:
  #     threshold: 4

  # return-statements:            # Functions or methods with a high number of return statements
  #   config:
  #     threshold: 4

  # similar-code:                 #  Duplicate code which is not identical but shares the same structure (e.g. variable names may differ)
  #   config:
  #     threshold: # language-specific defaults. an override will affect all languages.

  # identical-code:               # Duplicate code which is syntactically identical (but may be formatted differently)
  #   config:
  #     threshold: # language-specific defaults. an override will affect all languages.

plugins:
  sonar-python:
    enabled: true
  bandit:
    enabled: true
  duplication:
    enabled: true

exclude_patterns:
  - "ckan/lib/search/index.py" # contains regular expression that cannot be parsed py CodeClimate
  - "**/*.js"
  - "**/tests/"
